# Generated by Django 5.2.9 on 2025-12-05 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('assignment_type', models.CharField(choices=[('homework', 'Домашняя работа'), ('classwork', 'Работа на уроке'), ('test', 'Контрольная работа')], default='homework', max_length=20, verbose_name='Тип задания')),
                ('exercise_type', models.CharField(choices=[('spelling', 'Правописание (Spelling)'), ('drag_and_drop', 'Перетаскивание (Drag and Drop)'), ('letter_soup', 'Буквенный суп (Letter Soup)')], default='spelling', max_length=20, verbose_name='Вид упражнения')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('graded', 'Проверено')], default='not_started', max_length=20, verbose_name='Статус')),
                ('attempts', models.IntegerField(default=0, verbose_name='Количество попыток')),
                ('exercise_data', models.JSONField(default=dict, verbose_name='Данные упражнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_exercises', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['-created_at'],
            },
        ),
    ]
