# Generated by Django 5.2.9 on 2025-12-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_data',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(default='spelling_drag_drop', max_length=50, verbose_name='Тип упражнения'),
        ),
    ]
