# Generated by Django 5.2.9 on 2025-12-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_remove_exercise_exercise_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSoupExercise',
            fields=[
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lettersoupexercise', serialize=False, to='exercises.exercise')),
                ('words', models.JSONField(default=list, verbose_name='Слова для поиска')),
                ('grid', models.JSONField(default=list, verbose_name='Сетка букв')),
                ('placed_words', models.JSONField(default=list, verbose_name='Размещенные слова')),
                ('grid_size', models.IntegerField(default=15, verbose_name='Размер сетки')),
                ('include_backwards', models.BooleanField(default=True, verbose_name='Включать обратное направление')),
                ('include_diagonals', models.BooleanField(default=False, verbose_name='Включать диагонали')),
            ],
            options={
                'verbose_name': 'Letter Soup упражнение',
                'verbose_name_plural': 'Letter Soup упражнения',
            },
        ),
        migrations.CreateModel(
            name='SpellingDragDropExercise',
            fields=[
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spellingdragdropexercise', serialize=False, to='exercises.exercise')),
                ('type', models.CharField(choices=[('spelling', 'Правописание (Spelling)'), ('drag_and_drop', 'Перетаскивание (Drag and Drop)')], default='spelling', max_length=20, verbose_name='Тип упражнения')),
                ('pairs', models.JSONField(default=list, verbose_name='Пары слов')),
                ('shuffle_letters', models.BooleanField(default=True, verbose_name='Перемешивать буквы')),
                ('show_hints', models.BooleanField(default=True, verbose_name='Показывать подсказки')),
            ],
            options={
                'verbose_name': 'Spelling/Drag & Drop упражнение',
                'verbose_name_plural': 'Spelling/Drag & Drop упражнения',
            },
        ),
    ]
