# Generated by Django 5.2.9 on 2025-12-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_lettersoupexercise_spellingdragdropexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettersoupexercise',
            name='pairs',
            field=models.JSONField(default=list, verbose_name='Пары слов'),
        ),
    ]
