# Generated by Django 5.2.9 on 2025-12-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_lettersoupexercise_pairs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragDropExercise',
            fields=[
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dragdropexercise', serialize=False, to='exercises.exercise')),
                ('pairs', models.JSONField(default=list, verbose_name='Пары слов')),
                ('shuffle_letters', models.BooleanField(default=True, verbose_name='Перемешивать буквы')),
                ('show_hints', models.BooleanField(default=True, verbose_name='Показывать подсказки')),
            ],
            options={
                'verbose_name': 'Drag & Drop упражнение',
                'verbose_name_plural': 'Drag & Drop упражнения',
            },
        ),
    ]
