# Generated by Django 5.2.9 on 2025-12-23 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_dragdropexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellingExercise',
            fields=[
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spellingexercise', serialize=False, to='exercises.exercise')),
                ('pairs', models.JSONField(default=list, verbose_name='Пары слов')),
                ('show_hints', models.BooleanField(default=True, verbose_name='Показывать подсказки')),
                ('require_correct_spelling', models.BooleanField(default=True, verbose_name='Требовать правильное написание')),
            ],
            options={
                'verbose_name': 'Spelling упражнение',
                'verbose_name_plural': 'Spelling упражнения',
            },
        ),
    ]
