# Generated by Django 5.2.9 on 2025-12-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_spellingexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dragdropexercise',
            name='shuffle_letters',
        ),
        migrations.AddField(
            model_name='dragdropexercise',
            name='use_only_word_letters',
            field=models.BooleanField(default=False, help_text='Если включено, в пуле будут только буквы из слова. Если выключено, будут добавлены случайные буквы.', verbose_name='Использовать только буквы из слова'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(default='drag_drop', max_length=50, verbose_name='Тип упражнения'),
        ),
        migrations.DeleteModel(
            name='SpellingDragDropExercise',
        ),
    ]
