# Generated by Django 5.2.9 on 2025-12-04 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentword',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='studentword',
            name='note',
        ),
        migrations.AddField(
            model_name='studentword',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_words_by_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Назначено учителем'),
        ),
    ]
