# Generated by Django 5.2.9 on 2025-12-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_remove_studentword_due_date_remove_studentword_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentword',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('learning', 'Изучается'), ('review', 'Повторение'), ('completed', 'Изучено')], default='new', max_length=10),
        ),
    ]
