# Generated by Django 5.2.9 on 2025-12-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_studentword_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentword',
            name='correct_answers',
            field=models.IntegerField(default=0, verbose_name='Правильных ответов'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее повторение'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='next_review',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующее повторение'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='Количество повторений'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='wrong_answers',
            field=models.IntegerField(default=0, verbose_name='Неправильных ответов'),
        ),
        migrations.AlterField(
            model_name='studentword',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('learning', 'Изучается'), ('review', 'Повторение'), ('completed', 'Изучено')], default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
