# Generated by Django 5.2.9 on 2025-12-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_studentword_correct_answers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
