# Generated by Django 5.2.9 on 2025-12-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_delete_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentword',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='studentword',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='studentword',
            name='next_review',
        ),
        migrations.RemoveField(
            model_name='studentword',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='studentword',
            name='wrong_answers',
        ),
    ]
