# Generated by Django 5.2.9 on 2025-12-07 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_remove_studentword_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentword',
            name='avg_response_time',
            field=models.FloatField(default=0.0, verbose_name='Среднее время ответа (мс)'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='Текущая серия правильных'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Первое знакомство'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentword',
            name='last_correct_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний правильный ответ'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее взаимодействие'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='longest_streak',
            field=models.IntegerField(default=0, verbose_name='Лучшая серия правильных'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='times_attempted',
            field=models.IntegerField(default=0, verbose_name='Попыток ответа'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='times_correct',
            field=models.IntegerField(default=0, verbose_name='Правильных ответов'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='times_seen',
            field=models.IntegerField(default=0, verbose_name='Показов слова'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='times_wrong',
            field=models.IntegerField(default=0, verbose_name='Неправильных ответов'),
        ),
        migrations.AddField(
            model_name='studentword',
            name='total_response_time',
            field=models.IntegerField(default=0, verbose_name='Общее время ответов (мс)'),
        ),
    ]
